### PR TITLE
Update my readme file

### PR DESCRIPTION
**Pull request by amay1612**

### CODE REVIEW

**Comment by vyom153069** [comment]
did you deleted original readme.md file?
make another PR and insure you don't have to change original readme.md file , you have to just add YOUR_NAME.md file. so i am closing this Pull request.

**Comment by amay1612** [comment]
Good Afternoon sir...
We have to write our intro just below the content of readme file..??

**Comment by vyom153069** [comment]
no , you have to add another file which will be like amay.md containing your intro

**Comment by amay1612** [comment]
ohl sir... thanku..

**Pull request closed without merging**
