### PR TITLE
Create my readme file

### PR DESCRIPTION
**Pull request by amay1612**

### CODE REVIEW

**Comment by vyom153069** [comment]
@amay1612 good work ! you can make it more good if you want.

**Comment by amay1612** [comment]
how can i do better...??
plzz explain

**Comment by vyom153069** [comment]
You can use headings ,list , etc 
For more you can refer this
 https://blog.bitsrc.io/how-to-write-beautiful-and-meaningful-readme-md-for-your-next-project-897045e3f991

**Comment by amay1612** [comment]
thanku for sharing this...
So may i correct it or not.???

**Comment by vyom153069** [comment]
i have merged your PR so now it is on you , if you want to change for learning purpose you can change this .if you don't want then also no prob.

**Pull request merged**
